### ISSUE TITLE
Update TOC for latest patches?

### ISSUE THREAD

**Issue by Narrosh** [kaandemiroz/DBM-CountPack-Asmongold#1]
Hey there, I was just wondering if you could update the TOC file for the new patches. Still works if I enable out of date addons in the game, but I'd appreciate it if fixed lol.

**Comment by kaandemiroz** [comment]
Yes, for sure! It's funny as I was just now looking into addon management tasks as the CurseForge deprecation was completed. I believe I had originally not updated it due to other official countdown packs not being updated, but it's true that there probably shouldn't be any reason to not update the TOC for this particular pack.

**Comment by kaandemiroz** [comment]
Updated in commit 21cbb4faef4c630c05565a4e34c32c906969d3d2
